version: "3"

services:
  base:
    build:
      context: ./base
    container_name: base
    ports:
      - 4200:4200
    volumes:
      - ./base:/base

  vue-app:
    build:
      context: ./vue-app
    container_name: vue-app
    ports:
      - 8080:8080
    volumes:
      - ./vue-app:/vue-app
